#!/bin/bash

echo ''
date
echo ''

list="21 22 23 24 25 31 32 33 34 35 41 42 43 44 45"

for i in $list
do
# {
	#ip="172.28.2.${i}"
	./restart $i
	sleep 0.5
# } &
done

# wait

echo ''
date
echo ''