#!/bin/bash

cmd=$1

echo ''
date

list="21 22 23 24 25 31 32 33 34 35 41 42 43 44 45"
#list="22 33"
for i in $list
do
#{
	#ip="172.28.2.${i}"
	./xcmd $i "$cmd"
	sleep 1
#} &
done

#wait

date
echo ''
