#!/bin/bash

file=$1
dir=$2


date
echo ''

arr=()

list="11 12 13 14 15 21 22 23 24 25 31 32 33 34 35 41 42 43 44 45"
for i in $list
do
# {
	ip="172.28.2.${i}"
	./xscp $ip $file $dir
	sleep 0.5
	#echo ''
	#$arr+=(${i})
# } &
done

# wait

#for j in $arr
#for j in $list
#do
#	echo "$j : OK."
#	echo ''
#done
echo ''
date